# Generated by Django 4.0.3 on 2022-06-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_ingredients_meals_review_type_delete_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='Type',
            new_name='type',
        ),
    ]
