# Generated by Django 4.0.3 on 2022-06-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_type_meals_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredients_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meals',
            name='meals_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='type',
            name='type_name',
            field=models.CharField(max_length=50),
        ),
    ]
